signalAction:
  updateVariant: "updateVariant"
  updateRenidition: "updateRenidition"
  updateSegment: "updateSegment"
  updatePart: "updatePart"
  updateDemuxSegement: "updateDemuxPart"
  updateDemuxPart: "updateDemuxPart"
  ping: "ping"
  abort: "abort"
  terminate: "terminate"
  ackVariant: 'ackVariant'
  ackRendition: 'ackRendition'
  ackSegment: 'ackSegment'
  ackPart: 'ackPart'
  ackDemuxSegment: 'ackDemuxSegment'
  ackDemuxPart: 'ackDemuxPart'
  pong: 'pong'
  aborted: 'aborted'
  terminated: 'terminated'